export const phoneNumberData = [
  { country: 'vi', countryName: 'Vietnam', code: '+84', regex: '^\\d{9,10}$' },
  { country: 'en', countryName: 'United States', code: '+1', regex: '^\\d{10}$' },
  { country: 'ja', countryName: 'Japan', code: '+81', regex: '^\\d{9,10}$' },
  { country: 'ko', countryName: 'South Korea', code: '+82', regex: '^\\d{9,10}$' },
  { country: 'cn', countryName: 'China', code: '+86', regex: '^\\d{11}$' },
  { country: 'th', countryName: 'Thailand', code: '+66', regex: '^\\d{8,9}$' },
  { country: 'ms', countryName: 'Singapore', code: '+65', regex: '^\\d{8}$' },
  { country: 'ms', countryName: 'Malaysia', code: '+60', regex: '^\\d{9,10}$' },
  { country: 'tl', countryName: 'Philippines', code: '+63', regex: '^\\d{9,10}$' },
  { country: 'id', countryName: 'Indonesia', code: '+62', regex: '^\\d{9,11}$' },
  { country: 'hi', countryName: 'India', code: '+91', regex: '^\\d{10}$' },
  { country: 'en-AU', countryName: 'Australia', code: '+61', regex: '^\\d{9}$' },
  { country: 'fr', countryName: 'France', code: '+33', regex: '^\\d{9}$' },
  { country: 'de', countryName: 'Germany', code: '+49', regex: '^\\d{10}$' },
  { country: 'en-GB', countryName: 'United Kingdom', code: '+44', regex: '^\\d{10}$' },
  { country: 'it', countryName: 'Italy', code: '+39', regex: '^\\d{9,10}$' },
  { country: 'es', countryName: 'Spain', code: '+34', regex: '^\\d{9}$' },
  { country: 'en-CA', countryName: 'Canada', code: '+1', regex: '^\\d{10}$' },
  { country: 'ru', countryName: 'Russia', code: '+7', regex: '^\\d{10}$' },
  { country: 'pt', countryName: 'Brazil', code: '+55', regex: '^\\d{10,11}$' },
  { country: 'af', countryName: 'South Africa', code: '+27', regex: '^\\d{9}$' },
  { country: 'ar', countryName: 'Egypt', code: '+20', regex: '^\\d{9,10}$' },
  { country: 'en-NG', countryName: 'Nigeria', code: '+234', regex: '^\\d{9,10}$' },
  { country: 'es-MX', countryName: 'Mexico', code: '+52', regex: '^\\d{10}$' },
  { country: 'es-AR', countryName: 'Argentina', code: '+54', regex: '^\\d{10,11}$' },
  { country: 'es-CL', countryName: 'Chile', code: '+56', regex: '^\\d{9,10}$' },
  { country: 'es-CO', countryName: 'Colombia', code: '+57', regex: '^\\d{10}$' },
  { country: 'ur', countryName: 'Pakistan', code: '+92', regex: '^\\d{9,10}$' },
  { country: 'ar-SA', countryName: 'Saudi Arabia', code: '+966', regex: '^\\d{8,9}$' },
  { country: 'ar-AE', countryName: 'United Arab Emirates', code: '+971', regex: '^\\d{9}$' },
]
